In [28]:
import numpy as np
 
result = np.array([1,3,5,7,9])
print(result)

result = np.arange(1,10)
result = np.arange(10,100,5)
result = np.zeros(10)  
result = np.ones(10)
result = np.linspace(0,100,5) # beş eşit aralığa böl
result = np.linspace(0,1,9)
result = np.random.randint(0,10)
result = np.random.randint(20)
result = np.random.randint(1,11,10)
result = np.random.rand(5) # 0-1 arası 5 sayı
result = np.random.randn(5) # -1 +1 arası 5 sayı
array = np.arange(50)
result= array.reshape(5,10)
print(result)
print(result.sum(axis=1))
print(result.sum(axis=0))

result = np.random.randint(1,101,15)
max= result.max()
min = result.min()
mean = result.mean()
index = result.argmax()
index = result.argmin()
sort = result.sort()


[1 3 5 7 9]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]
