In [7]:
import numpy as np 

numbers = np.array([0,5,10,15,20,25,50,75,100])

result = numbers[5]
result = numbers[-1]
result = numbers[0:3]
result = numbers[:5]
result = numbers[5:]
result = numbers[::] # bütün liste
result = numbers[::-1]
result = numbers[::-2]



In [20]:
numbers2 = np.array([[0,5,10],[15,20,25],[50,75,100]])
print(numbers2)
numbers2[0,2]
numbers2[:,2]
numbers2[:,0:2]
numbers2[-1,:]
numbers2[:3,:3]

[[  0   5  10]
 [ 15  20  25]
 [ 50  75 100]]


array([[  0,   5,  10],
       [ 15,  20,  25],
       [ 50,  75, 100]])

In [25]:
arr1 = np.arange(0,10)
arr2 = arr1 #reference 
arr3 = arr1.copy()
arr1,arr2

arr2[0] = 20
arr2,arr1,arr3

(array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))