In [44]:
import numpy as np
numbers1 = np.random.randint(10,101,6)
numbers2 = np.random.randint(10,101,6)

print(numbers1)
print(numbers2)

result = numbers1+numbers2
print(result)

print(numbers1+10)
result = numbers1-numbers2
print(result)



[13 98 74 67 74 84]
[89 41 25 64 39 97]
[102 139  99 131 113 181]
[ 23 108  84  77  84  94]
[-76  57  49   3  35 -13]


In [46]:
result = np.sin(numbers1)
result = np.cos(numbers1)

log= np.log(numbers1)
sqrt= np.sqrt(numbers2)

matris1 = numbers1.reshape(2,3)
matris2 = numbers2.reshape(2,3)
matris1,matris2



(array([[13, 98, 74],
        [67, 74, 84]]),
 array([[89, 41, 25],
        [64, 39, 97]]))

In [51]:
result =np.vstack( (matris1,matris2))
result
result =np.hstack( (matris1,matris2))
result

array([[13, 98, 74, 89, 41, 25],
       [67, 74, 84, 64, 39, 97]])

In [57]:
buyuk = numbers1 >=25
print(buyuk)
mod = numbers1%2 ==0
print(mod)

print(numbers1[mod])

[False  True  True  True  True  True]
[False  True  True False  True  True]
[98 74 74 84]
