10,15,30,45,60 degerlerine ahip numpy dizisini oluşturunuz.

In [5]:
import numpy as np

In [6]:
dizi = np.array([10,15,30,45,60])
print(dizi)

[10 15 30 45 60]


5-15  aralığına sahip dizi oluturun

In [7]:
dizi1 = np.arange(5,16)
print(dizi1)

[ 5  6  7  8  9 10 11 12 13 14 15]


50-100 arası 5 er artan diziyi oluşturun

In [8]:
dizi2 = np.arange(50,100,5)
print(dizi2)

[50 55 60 65 70 75 80 85 90 95]


10 elemanlı sıfırlardan oluşan bir dizi olul-şturalım

In [9]:
dizi3 = np.zeros(10)
print(dizi3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10 elemanlı birlerden oluşan bir dizioluşturun

In [10]:
dizi4 = np.ones(10)
print(dizi4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


0 ile 100 arasında 5 eşit aralıklı dizi ouluşturun

In [12]:
dizi5 = np.linspace(0,100,5)
print(dizi5)

[  0.  25.  50.  75. 100.]


10-30 arasında 5 tane rastgele sayı üretiniz

In [19]:
dizi6= np.random.randint(10,30,5)
print(dizi6)

[24 14 25 12 18]


-1 ile 1 arasında 10 sayı üretin

In [20]:
dizi7=np.random.randn(10)
print(dizi7)

[-0.18502504 -0.913565    0.74472933 -1.1641477   0.14448509  0.16338219
  0.22136599  0.25705686 -1.30520934  1.1792062 ]


3x5 boyutunda 10-50 arası rastgee bir matris olusturun

In [22]:
dizi8 = np.random.randint(10,50,15)
dizi8 = dizi8.reshape(3,5)
print(dizi8)

[[34 21 10 38 20]
 [35 18 37 21 20]
 [30 15 49 40 14]]


üretilen matrisin sütün ve satır toplamları

In [24]:
sum = dizi8.sum(axis=1)
print(sum)
sum = dizi8.sum(axis=0)
print(sum)

[123 131 148]
[99 54 96 99 54]


dizinin max,min ve mean değerlerini bulunuz

In [27]:
min = dizi8.min()
max = dizi8.max()
mean = dizi8.mean()

print(min,max,mean)


10 49 26.8


n büyük sayının imndexi nedir


In [29]:
argmax  = dizi8.argmax()
print(argmax)

12


10-20 değerlerini içeren dizinin ilk üç elemanını getiren sorgu

In [30]:
dizi9= np.arange(10,20)

ilk3 = dizi9[:3]
print(ilk3)


[10 11 12]


dizinin elemanlarını tersten yazdırın


In [32]:
print(dizi9[::-1])

[19 18 17 16 15 14 13 12 11 10]


dizi8 ilk satırını getirin

In [36]:
ilkSatir= dizi8[0]
print(dizi8)
print(ilkSatir)

[[34 21 10 38 20]
 [35 18 37 21 20]
 [30 15 49 40 14]]
[34 21 10 38 20]


2. satır 3. sütundaki elemanı getirin

In [47]:
ikiUc = dizi8[1,2]
print(ikiUc)

37


satırların ilk elemanını getirin

In [54]:
ilkeleman = dizi8[:,0]
print(ilkeleman)

[34 35 30]


matrisin değerlerinin karesini hesaplayın

In [55]:
dizi10 = dizi8 **2
print(dizi8)
print(dizi10)

[[34 21 10 38 20]
 [35 18 37 21 20]
 [30 15 49 40 14]]
[[1156  441  100 1444  400]
 [1225  324 1369  441  400]
 [ 900  225 2401 1600  196]]


-50 +50 aralığındaki dizinin pozitif çift elemanlarını yazdırın

In [70]:
dizi11 = np.random.randint(-50,50,25)
dizi11 = dizi11.reshape(5,5)

pozitif = dizi11 >=0 
cift =  dizi11%2==0
islem = pozitif*cift

print(dizi11)
print(dizi11[islem])


[[ -4 -16   3  45 -45]
 [ 34  42  24  33  -7]
 [-23   3  46  20  -6]
 [ 14  16  44  36 -23]
 [ 15  42  48   5  25]]
[34 42 24 46 20 14 16 44 36 42 48]
